[project]
name = "drone-pro-max"
version = "0.2.5"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gymnasium>=1.2.3",
    "mavsdk>=3.15.3",
    "noise>=1.2.2",
    "numpy>=2.4.4",
    "pymavlink>=2.4.49",
    "pyvista>=0.47.2",
    "stable-baselines3>=2.8.0",
    "torch>=2.11.0",
]
